version: '3.8'

services:
  devhive:
    build: ./devhive_app
    volumes:
      - ./devhive_app:/opt/services/djangoapp/src
      - ./devhive_app/staticfiles:/opt/services/djangoapp/staticfiles
    command: gunicorn --chdir /opt/services/djangoapp/src/ devhive.wsgi:application --bind 0.0.0.0:8000 --workers 4
    depends_on:
      - redis
    environment:
      SECRET_KEY: "!x)ppd8b354#ws@ui35k08o8+avuy1*s^k0nx$)tl%0%-m%g07"
    restart: always
    networks:
      custom_network:
        ipv4_address: 172.18.0.2
    extra_hosts:
      - "admin-panel:172.18.0.5"

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./devhive_app/config/nginx/conf.d:/etc/nginx/conf.d
      - ./devhive_app/staticfiles:/static
    depends_on:
      - devhive
    restart: always
    networks:
      custom_network:
        ipv4_address: 172.18.0.3

  redis:
    image: redis:latest
    command: redis-server --save "" --appendonly no --protected-mode no
    restart: always
    networks:
      custom_network:
        ipv4_address: 172.18.0.4

  admin:
    build: ./admin_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: adminDB
      DB_USER: admin
      DB_PASS: 1z^4A6U9N0pf7#doVkNzNEf&PKED^GCa
    restart: always
    networks:
      custom_network:
        ipv4_address: 172.18.0.5
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: o4cYZ7Mr5O5zephjJ4aG7hE2
      MYSQL_DATABASE: adminDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1z^4A6U9N0pf7#doVkNzNEf&PKED^GCa
    volumes:
      - db_data:/var/lib/mysql
      - ./admin_app/db/adminDB.sql:/docker-entrypoint-initdb.d/data.sql
    restart: always
    networks:
      custom_network:
        ipv4_address: 172.18.0.6

volumes:
  db_data:


networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
